apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    ansible/role: argo-workflows
    as: cluster-admin
  name: argo-admin
  namespace: {{ namespace }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    ansible/role: argo-workflows
    as: cluster-admin
  name: argo-admin
  namespace: {{ namespace }}
roleRef:
  kind: Role
  name: argo-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:admin
    namespace: {{ namespace }}
