kind: Kustomization

commonLabels:
  ansible/role: argo-workflows

resources:
  # Argo
  - namespace-install.yaml
  # Custom manifests
  - secrets.yaml
  - view.yaml
  - workflow-creator.yaml
  - workflow-observer.yaml
