# Grant argo SA "view" access to the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    ansible/role: argo-workflows
  name: view
  namespace: {{ namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: workflow-creator
  namespace: {{ namespace }}
