# This is a convenient role to be able to use the Argo CLI
# to list workflows as any authenticated user (i.e., developer)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-creator
  labels:
    ansible/role: argo-workflows
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-creator
  labels:
    ansible/role: argo-workflows
roleRef:
  kind: Role
  name: workflow-creator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: workflow-creator
