# This is a convenient role to be able to use the Argo CLI
# to list workflows as any authenticated user (i.e., developer)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-observer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-observer
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-observer
roleRef:
  kind: Role
  name: workflow-observer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:authenticated
  - kind: ServiceAccount
    name: workflow-observer
