---
# tasks file to perform kustomize build and apply patches and overlays
- name: "setting fact for k8s root directory"
  set_fact: k8s_root="{{ role_path }}/files"

- name: "get root directory content"
  shell: |
    set -euxo pipefail
    type tree >/dev/null && tree {{ k8s_root }} || find {{ k8s_root }}
  args:
    executable: /bin/bash
  register: result
  changed_when: false

- name: "display root directory content"
  debug:
    var: result
    verbosity: 1

- name: "add secrets to the base kustomization file"
  command: "kustomize edit add resources secrets.yaml"
  args:
    chdir: "{{ k8s_root }}"
  when: artifactRepository == "s3"

- name: "kustomize"
  command: "kustomize build patch -o deploy.yaml"
  args:
    chdir: "{{ k8s_root }}"
  when: not overlay | length

- name: "kustomize with overlay: {{ overlay }}"
  command: "kustomize build overlays/{{ overlay }}/{{ as }} -o deploy.yaml"
  args:
    chdir: "{{ k8s_root }}"
  when: overlay | length
