---
# tasks file for argo-workflows
- name: "setting fact for path to main deployment"
  tags:
    - deploy
  set_fact: deployment="{{ role_path }}/files/deploy.yaml"

- name: "setting fact for deployment command"
  tags:
    - deploy
  set_fact: command={{ "oc" if overlay == "openshift" else "kubectl" }}

- import_tasks: process_templates.yml
  tags:
    - templates

- import_tasks: kustomize.yml
  tags:
    - kustomize
    - kustomization

- name: "deploy as cluster-admin"
  tags:
    - deploy
    - cluster-admin
  command: |
    {{ command }} apply --namespace {{ namespace }} -f {{ deployment }} --validate={{ validate }}
  register: result
  when: role == "cluster-admin"
  changed_when: '"configured" in result.stdout'

- name: "deploy as developer"
  tags:
    - deploy
    - developer
  command: |
    {{ command }} apply --namespace {{ namespace }} -f {{ deployment }} -l as!=cluster-admin --validate={{ validate }}
  register: result
  when: role == "developer"
  changed_when: '"configured" in result.stdout'
