---
# tasks file for argo-workflows
- name: "setting fact for path to main deployment"
  set_fact: deployment="{{ role_path }}/files/deploy.yaml"

- import_tasks: process_templates.yml
  tags:
    - templates

- import_tasks: kustomize.yml
  tags:
    - kustomize
    - kustomization

- name: "check if namespace exists"
  command: "kubectl get ns {{ namespace }}"
  register: namespace_exists
  ignore_errors: yes

- name: "create a namespace"
  command: "kubectl create namespace {{ namespace }}"
  when: namespace_exists is failed

# TODO: find a way around this
# - name: "grant the service account required SCC"
#   command: "oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:{{ namespace }}:default"

- name: "deploy"
  command: "kubectl -n {{ namespace }} apply -f {{ deployment }}"
