---
# tasks file for argo-workflows
- name: "setting fact for path to main deployment"
  tags:
    - deploy
  set_fact: deployment="{{ role_path }}/files/deploy.yaml"

- import_tasks: process_templates.yml
  tags:
    - templates

- import_tasks: kustomize.yml
  tags:
    - kustomize
    - kustomization

- name: "create a namespace if not exists"
  tags:
    - deploy
    - cluster-admin
  k8s:
    state: present
    kind: Namespace
    name: "{{ namespace }}"
  when: as == "cluster-admin"

- name: "deploy as cluster-admin"
  tags:
    - deploy
    - cluster-admin
  command: kubectl apply --namespace {{ namespace }} -f {{ deployment }}
  when: as == "cluster-admin"

- name: "deploy as developer"
  tags:
    - deploy
    - developer
  command: kubectl apply --namespace {{ namespace }} -f {{ deployment }} -l as!=cluster-admin
  when: as == "developer"
