---
# tasks file for argo-workflows
- name: "setting fact for path to main deployment"
  set_fact: deployment="{{ role_path }}/files/deploy.yaml"

- import_tasks: process_templates.yml
  tags:
    - templates

- import_tasks: kustomize.yml
  tags:
    - kustomize
    - kustomization

- name: "create a namespace if not exists"
  tags:
    - deploy
    - namespace
  k8s:
    state: present
    kind: Namespace
    name: "{{ namespace }}"

- name: "deploy"
  tags:
    - deploy
  k8s:
    state: present
    src: "{{ deployment }}"
    namespace: "{{ namespace }}"
