---
- import_tasks: process_templates.yml
  tags:
    - templates

# tasks file for argo-workflows
- name: "check if namespace exists"
  command: "kubectl get ns {{ namespace }}"
  register: namespace_exists
  ignore_errors: yes

- name: "create a namespace"
  command: "kubectl create namespace {{ namespace }}"
  when: namespace_exists is failed

# TODO: create a proper rolebinding
- name: "create a rolebinding"
  command: "kubectl -n {{ namespace }} create rolebinding default-admin --clusterrole=admin --serviceaccount={{ namespace }}:default"
  ignore_errors: yes  # rb exists

# TODO: find a way around this
- name: "grant the service account required SCC"
  command: "oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:{{ namespace }}:default"

- name: "deploy"
  command: "kubectl -n {{ namespace }} apply -f {{ k8s_base }}"