---
# tasks file for template processing
- set_fact:
    argo_url: "https://raw.githubusercontent.com/argoproj/argo/master/manifests/namespace-install.yaml"
    k8s_base: "{{ role_path }}/files/base"

- name: "make sure directory for kubernetes templates exists"
  file:
    path: "{{ k8s_base}}"
    state: directory
    recurse: yes

- name: "get Argo"
  get_url:
    url:  "{{ argo_url }}"
    dest: "{{ k8s_base }}"

- name: "process artifact repository secrets template"
  template:
    src:  "{{ secrets }}"
    dest: "{{ k8s_base }}"
  when: ARTIFACT_REPOSITORY == "s3"

- name: "process workflow controller configmap template"
  template:
    src:  "{{ configmap }}"
    dest: "{{ k8s_base }}"

- name: "find kustomize resource configs"
  find:
    paths: "{{ k8s_base | dirname }}"
    file_type: file
    patterns:
      - 'kustomize.yaml'
      - 'kustomize.yml'
      - 'kustomize'
    recurse: yes
  register: resource_configs
    
- name: "kustomize"
  command: "kustomize build {{ item | dirname }}"
  when: resource_configs.matched
  with_items: resource_configs.files