---
# tasks file for template processing
- set_fact: argo_url="https://raw.githubusercontent.com/argoproj/argo/master/manifests/namespace-install.yaml"

# root directory for k8s files
- set_fact: k8s_root="{{ role_path }}/files"

# kubernetes deployment templates and overlays
- set_fact:
    k8s_base:  "{{ k8s_root }}/base"
    k8s_patch: "{{ k8s_root }}/patch"
    k8s_overlays: "{{ k8s_root }}/overlays"

- name: "make sure directories for kubernetes templates exist"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ k8s_root }}"
    - "{{ k8s_base }}"
    - "{{ k8s_patch }}"
    - "{{ k8s_overlays }}"

- name: "get argo"
  get_url:
    url:  "{{ argo_url }}"
    dest: "{{ k8s_base }}"

- name: "process artifact repository secrets template"
  template:
    src: ../templates/secrets.yaml
    dest: "{{ k8s_base }}"
  when: ARTIFACT_REPOSITORY == "s3"

- name: "process base templates"
  template:
    src:  "{{ item.src }}"
    dest: "{{ k8s_base }}"
  with_filetree: ../templates/base/

- name: "find all patche templates"
  find:
    paths: ../templates/patch
    file_type: file
    patterns:
      - '*.yaml'
      - '*.yml'
    excludes:
      - 'kustomization*'
    recurse: yes
  register: patche_templates

- name: "process patche templates"
  template:
    src:  "{{ item.path }}"
    dest: "{{ k8s_patch }}"
  with_items: "{{ patche_templates.files }}"

- name: "find all patches"
  find:
    paths: "{{ k8s_patch }}"
    file_type: file
    patterns:
      - '*.yaml'
      - '*.yml'
    recurse: yes
  register: patches

- name: "find all resources"
  find:
    paths: "{{ k8s_base }}"
    file_type: file
    patterns:
      - '*.yaml'
      - '*.yml'
    recurse: yes
  register: resources

- name: "find all kustomization templates"
  find:
    paths: ../templates
    file_type: file
    patterns:
      - 'kustomization.yaml'
      - 'kustomization.yml'
      - 'kustomization'
    recurse: yes
  register: kustomization_templates

- name: "process kustomization templates"
  template:
    src:  "{{ item.path }}"
    dest: "{{ k8s_root }}/{{ item.path | relpath( '../templates' ) }}"
  with_items: "{{ kustomization_templates.files }}"
