kind: Kustomization

commonLabels:
  ansible/overlay: openshift

resources:
  - image-builder.yaml
  - route.yaml

bases:
  # patch should always be applied
  - ../../{{ k8s_patch | relpath( k8s_overlays ) }}
