apiVersion: v1
kind: Secret
metadata:
  name: argo-artifact-repository-secrets
  labels:
    app: workflow-controller
type: Opaque
data:
  accessKey: "{{ AWS_S3_ACCESS_KEY_ID | b64encode }}"
  secretKey: "{{ AWS_S3_SECRET_ACCESS_KEY | b64encode }}"
