# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  labels:
    app: workflow-controller
data:
  config: |
    # Specifies the container runtime interface to use (default: docker)
    containerRuntimeExecutor: "{{ executor }}"

    # namespace limits the controller's watch/queries to a specific namespace. This allows the
    # controller to run with namespace scope (Role), instead of cluster scope (ClusterRole).
    namespace: "{{ namespace }}"

{% if artifactRepository == "s3" %}
    artifactRepository:
      # archiveLogs will archive the main container logs as an artifact
      archiveLogs: {{ archiveLogs }}

      s3:
        bucket: "{{ AWS_S3_BUCKET_NAME }}"
{% if AWS_S3_BUCKET_PREFIX != "" %}
        keyPrefix: "{{ AWS_S3_BUCKET_PREFIX }}/{{ AWS_S3_ARTIFACT_PATH }}"  # optional
{% endif %}
        endpoint: "{{ AWS_S3_HOST }}"
        insecure: true                  #omit for S3/GCS. Needed when minio runs without TLS
        accessKeySecret:                #omit if accessing via AWS IAM
          name: argo-artifact-repository-secrets
          key: accessKey
        secretKeySecret:                #omit if accessing via AWS IAM
          name: argo-artifact-repository-secrets
          key: secretKey
{% endif %}
