kind: Kustomization

patches:
- path: argo-role.yaml
  target:
    kind: Role
    name: argo-role
- path: custom-image.yaml
  target:
    kind: Deployment
    name: workflow-controller

patchesStrategicMerge:
- configmap.yaml

bases:
  - {{ k8s_base | relpath( k8s_patch ) }}
