kind: Kustomization

commonLabels:
  app: argo
  component: argo-workflows

patches:
- target:
    name: argo-role
    kind: Role
  path: argo-role.yaml

patchesStrategicMerge:
- configmap.yaml

bases:
  - {{ k8s_base | relpath( k8s_patch ) }}
