name: CI  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v1
    - name: Run Ansible Lint
      # replace "master" with any valid ref
      uses: cermakm/ansible-lint-action@master
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        targets: '.'

    - name: Prepare
      run: |
        # Make sure Ansible executes scripts in bash by default
        export SHELL=/bin/bash

        pushd ${GITHUB_WORKSPACE}/tests
        ln -sf ../ argo-workflows
        popd

        pip install --user kubernetes openshift

    - name: Check tasks
      run: |
        tasks=$(\
          ansible-playbook tests/test.yml --list-tasks |\
          grep argo-workflows  |\
          tee /dev/stderr |\
          wc -l \
        )
        if [ $tasks -le 0 ]; then
          >&2 echo 'Number of tasks is expected to be >= 0'
          exit 1
        fi

    - name: Check resources
      run: |
        set -euxo pipefail

        pushd {{ GITHUB_WORKSPACE }}
        ansible-playbook -v tests/test.yml --tags templates,kustomize

        required=(
          argo 
          argo-admin 
          argo-binding 
          argo-role 
          argo-ui 
          argo-ui-binding 
          argo-ui-role 
          workflow-controller 
          workflow-controller-configmap 
          workflows.argoproj.io 
          workflowtemplates.argoproj.io 
        )

        resources=$(cat files/deploy.yaml | yq -r '.metadata.name' | sort -u)
        for r in ${required[@]}; do
          >&2 echo "Checking resource '$r'"

          ret=$(case "${resources[@]}" in  *"$r"*) echo 0 ;; esac)
          if [ -z $ret ]; then
            >&2 echo "ERROR: Missing required resource '$r'"
            exit 1
          fi
        done
